### ISSUE TITLE
how can i quickly resize a character? 

### ISSUE THREAD

**Issue by henriavo** [alvaromontoro/CSS-Simpsons#1]
Hi I'm new to html and css. How can I quickly and easily resize a character. I'm looking for some sort of "50%" of original size attribute I can change. Thank you.

**Comment by alvaromontoro** [comment]
You can apply a `transform` at the drawing container level to scale it to the percentage that you want. For example, to make it 50% smaller, you could do:

```
.character {
  /* ... */
  transform: scale(50%);
}
```

You can see a demo here: https://codepen.io/alvaromontoro/pen/OJQmqww
